---
# tasks file for install_yubikey
- import_tasks: install_packages.yml

- include_tasks: pamu2cfg.yml
  when: "{{ lookup('fileglob', install_yubikey_u2f_mappings_file) | length }} == 0"

- include_tasks: pam.yml
  when: "{{ install_yubikey_configure_pam }}"
